FROM crac-17-checkpoint

COPY snapshot /home/app/snapshot
COPY target/spring-petclinic-3.4.0-SNAPSHOT.jar /home/app/target/spring-petclinic-3.4.0-SNAPSHOT.jar

WORKDIR /home/app

CMD ["-XX:CRaCRestoreFrom=/home/app/snapshot"]
